triggers: [ push ]
name: Benchmark
images:
  prisma_benchmark:
    base_image: ubuntu-22.04-bare
    tasks:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs
      - npm i -g pnpm@7 --unsafe-perm
      - pnpm i
      - echo hello
    rebuild:
      on_base_image_change: true
      on_file_change:
        - 'pnpm-lock.yaml'

executor:
  image: prisma_benchmark
  hardware: x86-2vcpu

tasks:
  - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs
  - npm i -g pnpm
  - apt-get -qy install openssl
  - pnpm i
  - pnpm run setup
  # This is required as setup can modify pnpm-lock.yml
  - rm -f ./pnpm-lock.yaml
  - ls /workspace/packages/client/src/__tests__/benchmarks/huge-schema/node_modules/.prisma/client
  - pnpm run bench