triggers: [ push ]
name: Benchmark
images:
  prisma_benchmark:
    base_image: ubuntu-22.04-bare
    tasks:
      - touch ~/.bashrc
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=v7.27.0 sh -
      - npm i --silent -g pnpm@7 --unsafe-perm
      - pnpm i

    rebuild:
      on_base_image_change: true
      on_file_change:
        - 'pnpm-lock.yaml'

executor:
  image: prisma_benchmark
  hardware: x86-2vcpu

tasks:
  - pnpm run setup
  - pnpm run bench