triggers: [push]
name: Benchmark
images:
  prisma_benchmark:
    base_image: ubuntu-22.04-github
    tasks:
      #      - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs
      #      - npm i -g pnpm@7 --unsafe-perm
      #      - pnpm i
      - echo hello
    rebuild:
      on_base_image_change: true
      on_file_change:
        - 'pnpm-lock.yaml'

executor:
  image: prisma_benchmark
  hardware: x86-2vcpu

tasks:
  - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs
  - CI=true SKIP_GIT=true bash .github/workflows/scripts/setup.sh
  # This is required as setup can modify pnpm-lock.yml
  - rm -f ./pnpm-lock.yaml
  - pnpm run bench
